const { SlashCommandBuilder, PermissionFlagsBits, ChannelType, EmbedBuilder } = require('discord.js');
const embeds = require('../utils/embeds');
const { number, parseDuration, calculateLevel } = require('../utils/format');
const Guild = require('../../models/Guild');
const Member = require('../../models/Member');
const Warning = require('../../models/Warning');
const Reminder = require('../../models/Reminder');
const Giveaway = require('../../models/Giveaway');
const Ticket = require('../../models/Ticket');
const Inventory = require('../../models/Inventory');
const ShopItem = require('../../models/ShopItem');
const ReactionRole = require('../../models/ReactionRole');

const truth = ['What is a secret you have never told this server?', 'What is your most embarrassing Discord moment?', 'Who was your first online friend?'];
const dare = ['Send your favorite meme.', 'Compliment the person above you.', 'Use only emojis for your next message.'];
const wyr = ['Would you rather have unlimited money or unlimited time?', 'Would you rather be invisible or be able to fly?', 'Would you rather give up games or music?'];
const jokes = ['Why did the developer go broke? Because they used up all their cache.', 'I told my bot a joke about UDP. It might get it.', 'There are 10 kinds of people: those who understand binary and those who do not.'];
const roasts = ['You bring everyone so much joy... when you stop typing.', 'Your Wi-Fi has more stable relationships than you.', 'You are proof that lag can become a personality.'];
const quotes = ['“Stay hungry, stay foolish.” — Steve Jobs', '“Simplicity is the ultimate sophistication.” — Leonardo da Vinci', '“It always seems impossible until it is done.” — Nelson Mandela'];
function pick(a){ return a[Math.floor(Math.random()*a.length)]; }
function opt(i,n){ return i.options?.getString?.(n) || i.options?.getInteger?.(n) || i.options?.getUser?.(n) || i.options?.getMember?.(n) || i.options?.getRole?.(n) || i.options?.getChannel?.(n); }
function amount(i){ const v=Number(opt(i,'amount')||0); return Number.isFinite(v)&&v>0?Math.floor(v):0; }
async function reply(i,p){ return embeds.safeReply(i,p); }
async function ensureGuild(id){ return Guild.findOneAndUpdate({guildId:id},{$setOnInsert:{guildId:id}},{upsert:true,new:true}); }
function base(name, desc){ return new SlashCommandBuilder().setName(name).setDescription(desc.slice(0,100)); }
function dataFor(name){ const b=base(name, descriptions[name]||`${name} command`);
  if(['ban','kick','softban','timeout','untimeout','warn','warnings','clearwarnings','nick','role','pay','rob','avatar','banner','userinfo','whois','dm','ship','add','remove','setlevel','resetxp'].includes(name)) b.addUserOption(o=>o.setName('user').setDescription('Target user').setRequired(['ban','kick','softban','timeout','warn','pay','dm'].includes(name)));
  if(['deposit','withdraw','gamble','coinflip','slots','pay','slowmode','purge','setlevel','resetxp'].includes(name)) b.addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(['deposit','withdraw','pay','purge'].includes(name)));
  if(['announce','embed','poll','8ball','translate','weather','reminder','gcreate','rename','afk','dm','nick','warn','ban','kick','softban','timeout'].includes(name)) b.addStringOption(o=>o.setName('text').setDescription('Text or reason').setRequired(['announce','poll','8ball','dm'].includes(name)));
  if(['gcreate','reminder','timeout'].includes(name)) b.addStringOption(o=>o.setName('duration').setDescription('Duration like 10m, 2h, 7d').setRequired(name==='gcreate'));
  if(['lock','unlock','slowmode','announce','poll','embed'].includes(name)) b.addChannelOption(o=>o.setName('channel').setDescription('Channel'));
  if(['role','rr'].includes(name)) b.addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(name==='role'));
  return b; }
const descriptions={botinfo:'Show bot information',guilds:'Show guild count',stats:'Show runtime stats',automod:'Toggle automod',filter:'Manage bad-word filters',language:'Set or view language',prefix:'Set or view prefix',settings:'Show server settings',coinflip:'Flip or bet coins',crime:'Attempt a risky crime',deposit:'Deposit coins',economyconfig:'Show economy config',gamble:'Gamble coins',inventory:'Show inventory',pay:'Pay another member',richlist:'Show richest members',rob:'Rob another member',shop:'Show shop items',slots:'Play slots',weekly:'Claim weekly coins',withdraw:'Withdraw coins',work:'Work for coins'};
async function execute(name,i,client){ const gid=i.guild?.id, uid=i.user.id; const text=opt(i,'text'); const target=opt(i,'user');
 switch(name){
  case 'botinfo': return reply(i,{embeds:[embeds.info('Bot Info',`Servers: ${client.guilds.cache.size}\nUsers cached: ${client.users.cache.size}\nCommands: ${client.commands.size}\nUptime: ${Math.floor(process.uptime()/60)} minutes`)]});
  case 'guilds': return reply(i,{embeds:[embeds.info('Guilds',client.guilds.cache.map(g=>`• ${g.name} (${g.memberCount||'?'})`).slice(0,20).join('\n')||'No guilds cached.')]});
  case 'stats': return reply(i,{embeds:[embeds.info('Stats',`Memory: ${Math.round(process.memoryUsage().rss/1024/1024)} MB\nPing: ${client.ws.ping}ms\nNode: ${process.version}`)]});
  case 'settings': {const g=await ensureGuild(gid); return reply(i,{embeds:[embeds.info('Settings',`Prefix: ${g.prefix}\nLanguage: ${g.language}\nModules: ${Object.entries(g.modules||{}).map(([k,v])=>`${k}:${v?'on':'off'}`).join(', ')}`)]});}
  case 'prefix': case 'language': {const set=text?.trim(); const field=name; const q=set?{$set:{[field]:set}}:{$setOnInsert:{guildId:gid}}; const g=await Guild.findOneAndUpdate({guildId:gid},q,{upsert:true,new:true}); return reply(i,{embeds:[embeds.success(name,set?`Set ${name} to ${set}`:`Current ${name}: ${g[field]}`)]});}
  case 'automod': {const g=await ensureGuild(gid); const enabled=!g.automod?.enabled; await Guild.updateOne({guildId:gid},{$set:{'modules.automod':enabled,'automod.enabled':enabled}}); return reply(i,{embeds:[embeds.success('Automod',`Automod is now ${enabled?'enabled':'disabled'}.`)]});}
  case 'filter': {const word=text?.trim(); if(word) await Guild.updateOne({guildId:gid},{$addToSet:{'automod.badWords.words':word},$set:{'automod.badWords.enabled':true,'automod.enabled':true,'modules.automod':true}},{upsert:true}); const g=await ensureGuild(gid); return reply(i,{embeds:[embeds.info('Filter',`Filtered words: ${(g.automod?.badWords?.words||[]).join(', ')||'none'}${word?'\nAdded: '+word:''}`)]});}
  case 'daily': case 'weekly': case 'work': case 'crime': {const cfg=(await ensureGuild(gid)).economy; const now=new Date(); const map={daily:['lastDaily',86400000,cfg.dailyAmount,cfg.dailyAmount],weekly:['lastWeekly',604800000,cfg.weeklyAmount,cfg.weeklyAmount],work:['lastWork',3600000,cfg.workMin,cfg.workMax],crime:['lastCrime',7200000,cfg.crimeMin,cfg.crimeMax]}; const [field,cd,min,max]=map[name]; const m=await Member.findOne({guildId:gid,userId:uid}).lean(); if(m?.[field]&&now-m[field]<cd) return reply(i,{embeds:[embeds.warn(name,'You are still on cooldown.')]}); const gain=Math.floor(Math.random()*(max-min+1))+min; await Member.updateOne({guildId:gid,userId:uid},{$inc:{wallet:gain},$set:{[field]:now}},{upsert:true}); return reply(i,{embeds:[(gain>=0?embeds.success:embeds.warn)(name,`${gain>=0?'Earned':'Lost'} ${number(Math.abs(gain))} coins.`)]});}
  case 'deposit': case 'withdraw': {const a=amount(i); const m=await Member.findOne({guildId:gid,userId:uid}).lean()||{}; if(!a) return reply(i,{embeds:[embeds.warn(name,'Enter a positive amount.')]}); if(name==='deposit'&&(m.wallet||0)<a) return reply(i,{embeds:[embeds.warn('Deposit','Not enough wallet coins.')]}); if(name==='withdraw'&&(m.bank||0)<a) return reply(i,{embeds:[embeds.warn('Withdraw','Not enough bank coins.')]}); await Member.updateOne({guildId:gid,userId:uid},{$inc:{wallet:name==='deposit'?-a:a,bank:name==='deposit'?a:-a}},{upsert:true}); return reply(i,{embeds:[embeds.success(name,`${name==='deposit'?'Deposited':'Withdrew'} ${number(a)} coins.`)]});}
  case 'pay': {const a=amount(i); if(!target||target.bot||target.id===uid||!a) return reply(i,{embeds:[embeds.warn('Pay','Choose a user and positive amount.')]}); const m=await Member.findOne({guildId:gid,userId:uid}).lean()||{}; if((m.wallet||0)<a) return reply(i,{embeds:[embeds.warn('Pay','Not enough coins.')]}); await Member.updateOne({guildId:gid,userId:uid},{$inc:{wallet:-a}},{upsert:true}); await Member.updateOne({guildId:gid,userId:target.id},{$inc:{wallet:a}},{upsert:true}); return reply(i,{embeds:[embeds.success('Pay',`Paid ${target} ${number(a)} coins.`)]});}
  case 'richlist': {const rows=await Member.find({guildId:gid}).sort({wallet:-1,bank:-1}).limit(10).lean(); return reply(i,{embeds:[embeds.info('Richlist',rows.map((m,n)=>`${n+1}. <@${m.userId}> — ${number((m.wallet||0)+(m.bank||0))}`).join('\n')||'No balances yet.')]});}
  case 'leaderboard': {const rows=await Member.find({guildId:gid}).sort({totalXp:-1}).limit(10).lean(); return reply(i,{embeds:[embeds.info('Leaderboard',rows.map((m,n)=>`${n+1}. <@${m.userId}> — level ${calculateLevel(m.totalXp||0).level}, ${number(m.totalXp||0)} XP`).join('\n')||'No XP yet.')]});}
  case 'inventory': {const inv=await Inventory.findOne({guildId:gid,userId:target?.id||uid}).lean(); return reply(i,{embeds:[embeds.info('Inventory',(inv?.items||[]).map(x=>`• ${x.name} x${x.quantity}`).join('\n')||'Inventory is empty.')]});}
  case 'shop': {const items=await ShopItem.find({guildId:gid}).limit(20).lean(); return reply(i,{embeds:[embeds.info('Shop',items.map(x=>`• ${x.name} — ${number(x.price)}: ${x.description||'No description'}`).join('\n')||'No shop items configured.')]});}
  case 'warnings': {const rows=await Warning.find({guildId:gid,userId:target?.id||uid,active:true}).lean(); return reply(i,{embeds:[embeds.info('Warnings',rows.map((w,n)=>`${n+1}. ${w.reason} — <@${w.moderatorId}>`).join('\n')||'No active warnings.')]});}
  case 'warn': {if(!target) return reply(i,{content:'Pick a user.',ephemeral:true}); await Warning.create({guildId:gid,userId:target.id,moderatorId:uid,reason:text||'No reason provided'}); return reply(i,{embeds:[embeds.success('Warn',`Warned ${target}: ${text||'No reason provided'}`)]});}
  case 'clearwarnings': {await Warning.updateMany({guildId:gid,userId:target?.id||uid},{$set:{active:false}}); return reply(i,{embeds:[embeds.success('Warnings','Cleared active warnings.')]});}
  case '8ball': return reply(i,{embeds:[embeds.info('8ball',`${text}\n🎱 ${pick(['Yes.','No.','Maybe.','Ask again later.','Definitely.'])}`)]});
  case 'truth': return reply(i,{embeds:[embeds.info('Truth',pick(truth))]}); case 'dare': return reply(i,{embeds:[embeds.info('Dare',pick(dare))]}); case 'wyr': return reply(i,{embeds:[embeds.info('Would You Rather',pick(wyr))]}); case 'joke': return reply(i,{embeds:[embeds.info('Joke',pick(jokes))]}); case 'roast': return reply(i,{embeds:[embeds.info('Roast',`${target||i.user}, ${pick(roasts)}`)]}); case 'quote': return reply(i,{embeds:[embeds.info('Quote',pick(quotes))]});
  case 'coinflip': {const win=Math.random()<.5; const side=pick(['Heads','Tails']); return reply(i,{embeds:[embeds.info('Coinflip',`${side}!${amount(i)?` You ${win?'won':'lost'} ${number(amount(i))} coins.`:''}`)]});}
  case 'slots': return reply(i,{embeds:[embeds.info('Slots',[0,1,2].map(()=>pick(['🍒','🍋','🔔','⭐','7️⃣'])).join(' | '))]});
  case 'serverinfo': return reply(i,{embeds:[embeds.info('Server Info',`Name: ${i.guild.name}\nMembers: ${i.guild.memberCount}\nChannels: ${i.guild.channels.cache.size}\nRoles: ${i.guild.roles.cache.size}`)]});
  case 'userinfo': case 'whois': {const u=target||i.user; return reply(i,{embeds:[embeds.info('User Info',`User: ${u}\nID: ${u.id}\nCreated: <t:${Math.floor(u.createdTimestamp/1000)}:F>`)]});}
  case 'avatar': {const u=target||i.user; return reply(i,{embeds:[new EmbedBuilder().setTitle(`${u.username}'s avatar`).setImage(u.displayAvatarURL({size:1024})).setColor(0x5865f2)]});}
  case 'poll': {const msg=await (opt(i,'channel')||i.channel).send({embeds:[embeds.info('Poll',text)]}); await msg.react('👍').catch(()=>{}); await msg.react('👎').catch(()=>{}); return reply(i,{content:'Poll created.',ephemeral:true});}
  case 'announce': return (opt(i,'channel')||i.channel).send({embeds:[embeds.info('Announcement',text)]}).then(()=>reply(i,{content:'Announcement sent.',ephemeral:true}));
  case 'reminder': {const ms=parseDuration(opt(i,'duration')||'1h'); await Reminder.create({guildId:gid,userId:uid,channelId:i.channel.id,message:text||'Reminder',remindAt:new Date(Date.now()+ms)}); return reply(i,{embeds:[embeds.success('Reminder',`I will remind you <t:${Math.floor((Date.now()+ms)/1000)}:R>.`)]});}
  default: return reply(i,{embeds:[embeds.info(name,`/${name} is active. Use its options to manage ${name.replace(/config$/,' configuration')}.`)]});
 }}
function buildCommand(name, category, aliases=[]){ return {data:dataFor(name),category,aliases,userPermissions:[],botPermissions:[],cooldown:5,guildOnly:true,execute:(i,c)=>execute(name,i,c),prefixExecute:async(message,args,client)=>execute(name,{guild:message.guild,user:message.author,member:message.member,channel:message.channel,options:{getString:(n)=>args.join(' '),getInteger:(n)=>Number(args[0]),getUser:()=>message.mentions.users.first(),getMember:()=>message.mentions.members.first(),getRole:()=>message.mentions.roles.first(),getChannel:()=>message.mentions.channels.first()},reply:o=>message.reply(o),deferReply:async()=>{},editReply:o=>message.reply(o)},client)}; }
module.exports={buildCommand};
